package com.donotmiss.backend.agentlog;

public enum AgentStepName {
    PROFILE_MEMORY,
    MCP_CONTEXT,
    QUERY_REWRITE,
    RETRIEVAL,
    HISTORY_LOAD,
    SCHEDULE_LOAD,
    GOAL_ANALYSIS,
    PLANNER_STABLE,
    PLANNER_SPRINT,
    PLANNER_EXPLORE,
    SCHEDULE_CHECK,
    CRITIC_REVIEW,
    LLM_RECOMMENDATION,
    GROWTH_TAG_EXTRACTION,
    GROWTH_TAG_VALIDATION,
    RULE_FALLBACK,
    RESPONSE_BUILD
}
