CREATE TABLE agent_bad_cases (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    case_key VARCHAR(40) NOT NULL,
    user_id VARCHAR(80) NOT NULL,
    agent_run_id BIGINT,
    run_type VARCHAR(48),
    source_type VARCHAR(32) NOT NULL,
    issue_type VARCHAR(64) NOT NULL,
    severity VARCHAR(24) NOT NULL,
    status VARCHAR(32) NOT NULL,
    page_url VARCHAR(500),
    module_key VARCHAR(80),
    user_message VARCHAR(2000) NOT NULL,
    expected_behavior VARCHAR(2000),
    actual_behavior VARCHAR(2000),
    root_cause_step VARCHAR(64),
    root_cause_summary VARCHAR(2000),
    relevant_artifact_ids JSON,
    analysis_json JSON,
    agent_memory_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    eval_case_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    resolution_summary VARCHAR(2000),
    reviewer_id VARCHAR(80),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    triaged_at DATETIME(6),
    resolved_at DATETIME(6),
    UNIQUE KEY uk_agent_bad_cases_case_key (case_key),
    INDEX idx_agent_bad_cases_user_created (user_id, created_at),
    INDEX idx_agent_bad_cases_status_created (status, created_at),
    INDEX idx_agent_bad_cases_run (agent_run_id),
    INDEX idx_agent_bad_cases_issue_status (issue_type, status),
    INDEX idx_agent_bad_cases_root_step (root_cause_step),
    CONSTRAINT fk_agent_bad_cases_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL
);
